# Generated by Django 5.2.4 on 2025-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_author_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
