# Generated by Django 5.2.4 on 2025-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
            preserve_default=False,
        ),
    ]
