<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-28 22:43
=======
# Generated by Django 5.2.4 on 2025-07-27 20:40
>>>>>>> aea86264ebf01363a67a1d20dbc3f7bce3c4d97b

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
=======
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
>>>>>>> aea86264ebf01363a67a1d20dbc3f7bce3c4d97b
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='relationship_app.author')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'author')},
            },
=======
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.author')),
            ],
>>>>>>> aea86264ebf01363a67a1d20dbc3f7bce3c4d97b
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255, unique=True)),
                ('books', models.ManyToManyField(blank=True, related_name='libraries', to='relationship_app.book')),
            ],
            options={
                'ordering': ['name'],
            },
=======
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('books', models.ManyToManyField(to='relationship_app.book')),
            ],
>>>>>>> aea86264ebf01363a67a1d20dbc3f7bce3c4d97b
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to='relationship_app.library')),
            ],
            options={
                'ordering': ['name'],
            },
=======
                ('user_name', models.CharField(max_length=100)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.library')),
            ],
>>>>>>> aea86264ebf01363a67a1d20dbc3f7bce3c4d97b
        ),
    ]
