# Generated by Django 5.2.4 on 2025-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.DateField(default='1930-01-01'),
            preserve_default=False,
        ),
    ]
