# Generated by Django 5.2.4 on 2025-07-31 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_author_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='relationship_app.author'),
        ),
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
