# Generated by Django 5.2.4 on 2025-07-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_remove_book_author_book_authors_library_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarian',
            name='employee_id',
            field=models.CharField(default='1001', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='relationship_app.author'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='library',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to='relationship_app.library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(related_name='libraries', to='relationship_app.book'),
        ),
        migrations.AlterField(
            model_name='library',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
